In [1]:
import pandas as pd
import numpy as np 

from fbprophet import Prophet
from fbprophet.plot import add_changepoints_to_plot

ModuleNotFoundError: No module named 'fbprophet'

In [ ]:
df_age = pd.read_csv("Age (1).csv")

In [ ]:
df_age.head()
df_age.rename(columns = {'population per age group' : 'pop','% per age group':'perc', 'Age group':'Age_group'}, inplace= True)

In [ ]:
df_age.head()

Area  Population per age group   perc     Age_group
0  United States                   39925147  0.123   0-9 years  
1   Massachusetts                    726905  0.106   0-9 years  
2          Boston                     62783  0.092   0-9 years  
3         Allston                       409  0.021   0-9 years  
4       Back Bay                        655  0.037   0-9 years

In [ ]:
df_age['Age_group'].unique()

array([' 0-9 years  ', ' 10 - 17  years  ', ' 18 - 19 years  ',
       ' 20 - 34 years  ', ' 35 - 59 years  ', ' 60 and Over  '],
      dtype=object)

In [ ]:
df = _deepnote_execute_sql('select Area, avg(perc) as avg_perc\nfrom \ndf_age\nwhere Area not in (\'Massachusetts\',\'United States\',\'Boston\')\nand \nAge_group in (\' 18 - 19 years  \',\' 20 - 34 years  \',\' 20 - 34 years  \')\ngroup by Area\norder by avg(perc) desc \nlimit 3', 'SQL_DEEPNOTE_DATAFRAME_SQL')
df

Area  avg_perc
0  Longwood    0.4830
1   Allston    0.3995
2    Fenway    0.3970

Longwood has the highest average perc population in the age groups from 18 - 34 (48.3%)

Allston has the second highest average perc population in the age groups from 18 - 34 (40%)

Fenway has the third highest average perc population in age groups from 18 - 34 (~40%)

In [ ]:
df_2 = _deepnote_execute_sql('\nselect Area, avg(perc) as avg_perc\nfrom \ndf_age\nwhere Area not in (\'Massachusetts\',\'United States\',\'Boston\')\nand \nAge_group in (\' 18 - 19 years  \',\' 20 - 34 years  \',\' 20 - 34 years  \')\ngroup by Area\norder by avg(perc)\nlimit 3', 'SQL_DEEPNOTE_DATAFRAME_SQL')
df_2

Area  avg_perc
0  West Roxbury    0.0955
1     Hyde Park    0.1135
2    Roslindale    0.1140

West Roxbury has the lowest avg population from the age 18 to 34 (9.6%)

Hyde Park has the second lowest avg population from the age 18 to 34 (11.34%)

Roslindale has the third lowest avg population from age 18 to 34 (11.40%)

Since the younger population will be more into time management and also into fitness areas with highest young population can be targeted

In [ ]:
df_income = pd.read_csv('per capita income.csv')

In [ ]:
df_income

Area Total population  \
0             United States      324,697,795   
1             Massachusetts        6,850,553   
2                    Boston          684,379   
3                   Allston           19,261   
4                  Back Bay           17,783   
5               Beacon Hill            9,648   
6                  Brighton           55,297   
7               Charlestown           19,890   
8                Dorchester          126,909   
9                  Downtown           18,306   
10              East Boston           47,263   
11                   Fenway           33,489   
12                Hyde Park           38,924   
13            Jamaica Plain           40,867   
14                 Longwood            5,351   
15                 Mattapan           26,659   
16             Mission Hill           17,386   
17                North End            8,749   
18               Roslindale           30,021   
19                  Roxbury           54,161   
20             South Boston           36,772   
21  South Boston Waterfront            4,403   
22                South End           32,571   
23                 West End            6,619   
24             West Roxbury           33,526   

    Aggregate income in the past 12 months (in 2019 Inflation-adjusted dollars)  \
0                                        1.107310e+13                             
1                                        2.997840e+11                             
2                                        3.058520e+10                             
3                                        6.577383e+08                             
4                                        1.968166e+09                             
5                                        9.648510e+08                             
6                                        2.281630e+09                             
7                                        1.498491e+09                             
8                                        3.777727e+09                             
9                                        1.465530e+09                             
10                                       1.487487e+09                             
11                                       9.384058e+08                             
12                                       1.274531e+09                             
13                                       2.110965e+09                             
14                                       4.267180e+07                             
15                                       7.559388e+08                             
16                                       4.076377e+08                             
17                                       7.847537e+08                             
18                                       1.238426e+09                             
19                                       1.136173e+09                             
20                                       2.380795e+09                             
21                                       5.708529e+08                             
22                                       2.723215e+09                             
23                                       5.101219e+08                             
24                                       1.603737e+09                             

    Per Capita Income  
0               34103  
1               43761  
2               44690  
3               34149  
4              110677  
5              100005  
6               41261  
7               75339  
8               29767  
9               80057  
10              31473  
11              28021  
12              32744  
13              51655  
14               7975  
15              28356  
16              23446  
17              89696  
18              41252  
19              20978  
20              64745  
21             129651  
22              83609  
23              77069  
24             

In [ ]:
df_income.rename(columns = {'Per Capita Income':'per_capita_income'}, inplace= True)

In [ ]:
df_income.head()

Area Total population  \
0  United States      324,697,795   
1  Massachusetts        6,850,553   
2         Boston          684,379   
3        Allston           19,261   
4       Back Bay           17,783   

   Aggregate income in the past 12 months (in 2019 Inflation-adjusted dollars)  \
0                                       1.107310e+13                             
1                                       2.997840e+11                             
2                                       3.058520e+10                             
3                                       6.577383e+08                             
4                                       1.968166e+09                             

   per_capita_income  
0              34103  
1              43761  
2              44690  
3              34149  
4             110677

In [ ]:
df_3 = _deepnote_execute_sql('select Area,per_capita_income\nfrom \ndf_income\nwhere Area not in (\'Massachusetts\',\'United States\',\'Boston\')\ngroup by Area, per_capita_income\norder by per_capita_income desc\nlimit 3', 'SQL_DEEPNOTE_DATAFRAME_SQL')
df_3

Area  per_capita_income
0  South Boston Waterfront             129651
1                 Back Bay             110677
2              Beacon Hill             100005

We can look into allocationg more resources in Beacon hill-

Number of universities -3

Per capita Income - High 

Number of coffee shops - less compared to other neighbourhoods

In [3]:
df_occ = pd.read_csv('Occupation.csv')

In [4]:
df_occ.head()

Area  Civilian employed population 16 years and over  \
0  United States                                       154842185   
1  Massachusetts                                         3612375   
2         Boston                                          381738   
3        Allston                                           10708   
4       Back Bay                                           11226   

   Population per occupation type  % of population per occupation type  \
0                        59647283                                0.385   
1                         1690459                                0.468   
2                          193226                                0.506   
3                            5846                                0.546   
4                            8365                                0.745   

                               Occupation   
0  Management, business, science, and arts  
1  Management, business, science, and arts  
2  Management, business, science, and arts  
3  Management, business, science, and arts  
4  Management, business, science, and arts

In [8]:
df_occ['Occupation '].unique()

array(['Management, business, science, and arts', 'Service',
       'Sales and office',
       'Natural resources, construction, and maintenance',
       'Production, transportation, and material moving'], dtype=object)

In [5]:
df_occ.columns

Index(['Area', 'Civilian employed population 16 years and over',
       'Population per occupation type', '% of population per occupation type',
       'Occupation '],
      dtype='object')

In [11]:
df_occ.rename(columns = {'% of population per occupation type':'pop_per_occ','Occupation ':'Occ'}, inplace= True)


In [12]:
df_occ.head()

Area  Civilian employed population 16 years and over  \
0  United States                                       154842185   
1  Massachusetts                                         3612375   
2         Boston                                          381738   
3        Allston                                           10708   
4       Back Bay                                           11226   

   Population per occupation type  pop_per_occ  \
0                        59647283        0.385   
1                         1690459        0.468   
2                          193226        0.506   
3                            5846        0.546   
4                            8365        0.745   

                                       Occ  
0  Management, business, science, and arts  
1  Management, business, science, and arts  
2  Management, business, science, and arts  
3  Management, business, science, and arts  
4  Management, business, science, and arts

In [23]:
df_4 = _deepnote_execute_sql('select Area,avg(pop_per_occ) as avg_perc\nfrom \ndf_occ\nwhere Occ = \'Service\'\ngroup by Area\norder by avg(pop_per_occ) desc\nlimit 3', 'SQL_DEEPNOTE_DATAFRAME_SQL')
df_4

Area  avg_perc
0  East Boston     0.382
1     Mattapan     0.296
2     Longwood     0.293

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=ec18e06e-4728-453d-a260-05d1606c6366' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>